// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these values by running: dart pub global activate flutterfire_cli && flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-HFLi5kussqTcExXXBR0vB88UxVm2-I',
    appId: '1:41932458800:web:164c20eef99b4759a856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    authDomain: 'habitcoach-7c9d4.firebaseapp.com',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
    measurementId: 'G-BWMS5XRH62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHBsvNUL8x3XgILXaVkgzyIwPVwNiQlGE',
    appId: '1:41932458800:android:4571726785385d96a856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_D7t3WR3tKDPF1aBlGJdkcVHj1tbjEbU',
    appId: '1:41932458800:ios:b1f9708115036b76a856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
    iosBundleId: 'com.habitcoachai.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_D7t3WR3tKDPF1aBlGJdkcVHj1tbjEbU',
    appId: '1:41932458800:ios:c0fca46e73ab5500a856f5',
    messagingSenderId: '41932458800',
    projectId: 'habitcoach-7c9d4',
    storageBucket: 'habitcoach-7c9d4.firebasestorage.app',
    iosBundleId: 'com.example.momentumAi',
  );
  static bool get isConfigured => true;
}
